CREATE TABLE IF NOT EXISTS `2400620` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  search_query VARCHAR(100) NOT NULL,
  query_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
